=== {learning-goals}

// tag::DE[]

[[LZ-5-1]]
==== LZ 5-1: Konflikte bedarfsgerecht analysieren

Um in Konfliktsituationen handlungs- und arbeitsfähig zu bleiben, sollten Teilnehmer:innen Konflikte mit Werkzeugen wie z.B.:

- Konfliktarten
- Konfliktstufen nach Glasl 

analysieren können. Sie sollten außerdem in einer Konfliktsituation erkennen können, ob sie den Konflikt eigenverantwortlich lösen können und geeignete  Deeskalations- und Delegationswege sowie weitere Lösungsstrategien ableiten können.

[[LZ-5-2]]
==== LZ 5-2: Eigenes Konfliktverhalten reflektieren

Teilnehmer:innen sollten verstehen, dass konstruktive Konfliktlösungen zu Wachstum und Lernen beitragen.
Außerdem sollte ihnen bewusst sein, welchen Anteil sie selbst, die Organisation, technologische Rahmenbedingungen und Zusammenarbeitsprozesse am Konflikt haben könnten.

[[LZ-5-3]]
==== LZ 5-3: Konflikte konstruktiv lösen und Präventionsmaßnahmen ableiten 

Da verschiedene Konfliktarten und -eskalationsstufen unterschiedliche Lösungswege in der Klärung benötigen, sollten Teilnehmer:innen diese kennen und anwenden können. Außerdem sollten sie Ansätze kennen, wie Konflikte auch präventiv behandelt werden können. 

// end::DE[]

// tag::EN[]


[[LG-5-1]]
==== LG 5-1: Analyze conflicts according to needs

In order to remain capable of acting and working in conflict situations, participants should be able to deal with conflicts using tools such as

- Types of conflict
- 9 stages of conflict escalation

to be able to analyze the situation. In a conflict situation, they should also be able to recognise whether they can resolve the conflict independently and derive suitable de-escalation and delegation methods as well as other solution strategies.

[[LG-5-2]]
==== LG 5-2: Reflect on own conflict behavior

Participants should understand that constructive conflict resolution contributes to growth and learning.
They should also be aware of the role that they themselves, the organization, technological constraints, and collaboration processes could play in the conflict.


[[LG-5-3]]
==== LG 5-3: Resolve conflicts constructively and derive preventive measures 

As different types of conflict and levels of escalation require different approaches to resolving them, participants should be familiar with these and be able to apply them. They should also know how conflicts can be dealt with preventively.

// end::EN[]
