=== {learning-goals}

// tag::DE[]

[[LZ-5-1]]
==== LZ 5-1: Konflikte bedarfsgerecht analysieren

Um in Konfliktsituationen handlungs- und arbeitsfähig zu bleiben, sollten Teilnehmer:innen Konflikte mit Werkzeugen wie z.B.:

- Konfliktarten
- Konfliktstufen nach Glasl 

analysieren können. Sie sollten außerdem in einer Konfliktsituation erkennen können, ob sie den Konflikt eigenverantwortlich lösen können und geeignete  Deeskalations- und Delegationswege sowie weitere Lösungsstrategien ableiten können.

[[LZ-5-2]]
==== LZ 5-2: Eigenes Konfliktverhalten reflektieren

Teilnehmer:innen sollten verstehen, dass konstruktive Konfliktlösungen zu Wachstum und Lernen beitragen.
Außerdem sollte ihnen bewusst sein, welchen Anteil sie selbst, die Organisation, technologische und Zusammenarbeitsprozesse am Konflikt haben könnten.

[[LZ-5-3]]
==== LZ 5-3: Konflikte lösen

Da verschiedene Konfliktarten und -eskalationsstufen unterschiedliche Lösungswege in der Klärung benötigen, sollten Teilnehmer:innen diese kennen und anwenden können. Außerdem sollten sie Ansätze kennen, wie Konflikte auch präventiv behandelt werden können. 

// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants can carry out a conflict analysis appropriate to the situation, to ensure a continued ability to act and work.
- In a conflict situation, the participants can recognise whether they can resolve the conflict on their own authority.
- The participants find both their own de-escalation channels and delegation options and escalation channels.

==== What should the participants understand?
- Different types of conflict require different approaches for their resolution.
- Conflict analyses assist in differentiating between practical and impractical solution approaches.
- Constructive conflict solutions contribute to growth and learning.
- Only under certain conditions can conflicts can be resolved on one’s own authority.
- The participants are not responsible for providing the solution for a conflict.

==== What should the participants know?
- The most important conflict situations in the context of software architecture work, and the involved parties (e. g., Specialist Department / Development, Development/Operations, Development/Support, etc.)
- Glasl’s stages of conflicts
- Conflict resolution options on one’s own authority
- Delegation options and escalation channels

[NOTE]
====
**TODO**: explizite Lernziele aus DE übernehmen
====


// end::EN[]
