=== {learning-goals}

// tag::DE[]
==== Was sollen die Teilnehmer können?
- Die TN können bedarfsgerecht eine Konfliktanalyse durchführen, um handlungs- und arbeitsfähig zu bleiben.
- Die TN können in einer Konfliktsituation erkennen, ob sie den Konflikt eigenverantwortlich lösen können.
- Die TN finden sowohl eigene Deeskalationswege als auch Wege der Delegation und Eskalation.

==== Was sollen die Teilnehmer verstehen?
- Verschiedene Konfliktarten benötigen unterschiedliche Lösungswege in der Klärung.
- Konfliktanalysen unterstützen darin, zweckmäßige von unzweckmäßigen Lösungswegen zu unterscheiden.
- Konstruktive Konfliktlösungen tragen zu Wachstum und Lernen bei.
- Konflikte lassen sich nur unter gewissen Voraussetzungen eigenverantwortlich lösen.
- Die TN sind nicht dafür verantwortlich, die Lösung für einen Konflikt zu liefern.

==== Was sollen die Teilnehmer kennen?
- Die für den Arbeitskontext der SW-Architektur wichtigsten Konfliktsituationen und deren Beteiligte (z. B. Fachbereich/Entwicklung, Entwicklung/Betrieb, Entwicklung/Support, usw.)
- Die Konfliktstufen nach Glasl
- Eigenverantwortliche Konfliktlösungswege
- Wege der Delegation und der Eskalation
// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants can carry out a conflict analysis appropriate to the situation, to ensure a continued ability to act and work.
- In a conflict situation, the participants can recognise whether they can resolve the conflict on their own authority.
- The participants find both their own de-escalation channels and delegation options and escalation channels.

==== What should the participants understand?
- Different types of conflict require different approaches for their resolution.
- Conflict analyses assist in differentiating between practical and impractical solution approaches.
- Constructive conflict solutions contribute to growth and learning.
- Only under certain conditions can conflicts can be resolved on one’s own authority.
- The participants are not responsible for providing the solution for a conflict.

==== What should the participants know?
- The most important conflict situations in the context of software architecture work, and the involved parties (e. g., Specialist Department / Development, Development/Operations, Development/Support, etc.)
- Glasl’s stages of conflicts
- Conflict resolution options on one’s own authority
- Delegation options and escalation channels
// end::EN[]

[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
