= https://isaqb.org[iSAQB] CPSA-Advanced Level Curriculum SOFT

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-soft/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-soft/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-soft.svg["Contributors",link="https://github.com/isaqb-org/curriculum-soft/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-soft.svg["Issues",link="https://github.com/isaqb-org/curriculum-soft/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-soft.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-soft/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum of the iSAQB CPSA-Advanced Level SOFT module in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request


== How to build the documents

Prerequisite: You need a Java Runtime(tm) 17 (or higher) installed.

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-foundation.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-foundation.git --recursive
----
--
. You build the output documents with gradle: `./gradle-tools/gradlew buildDocs`
That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.


== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Sebastian Hirschmeier, Stefan Zörner, and Kim Nena Duggen.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.

[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc
