=== {learning-goals}

// tag::DE[]

[[LZ-4-1]]
==== LZ 4-1: Die Verantwortlichkeiten einer Moderationsrolle verstehen

Die Teilnehmer:innen können zwischen Rolle „Moderation“ (mit absichtslosem Interesse am Ergebnis einen Lösungsprozess unterstützen) und Rolle „Entscheider“ (mit absichtsvollem Interesse am Ergebnis der Lösung mitwirken) unterscheiden. 
Sie sind in der Lage aus der Architekturrolle heraus zu entscheiden, wann empfängergerechte Beiträge hilfreich wären, um den Lösungsprozess zu unterstützen. Außerdem ist ihnen bewusst, welche Aufgaben und Verantwortlichkeiten Moderator:innen und Gesprächsteilnehmer:innen haben.

[[LZ-4-2]]
==== LZ 4-2: Eine Moderation inkl. passender Moderationswerkzeuge durchführen

Teilnehmer:innen können zur Unterstützung der Lösungsfindung und Konfliktprävention Methoden und Techniken zur Durchführung von Gruppensituationen sowie zur Gesprächsführung in Gruppen anwenden. Moderationstechniken könnten z.B. sein:

- Kreativitätstechniken wie Brainstorming
- Zuruf-/Kartenabfragen
- Dot Voting
- Time Boxing
- Mindmapping & Matrixdarstellungen


[[LZ-4-3]]
==== LZ 4-3: Entscheidungsfindung mit der Gruppe vorbereiten und durchführen

Für die Rolle „Entscheider“ (mit absichtsvollem Interesse am Ergebnis der Lösung mitwirken) und in der Rolle „Moderation“ können die Teilnehmer:innen geeignete Entscheidungsfindungswerkzeuge auswählen und Architekturentscheidungen in der Gruppe herbeizuführen. Geeignete Werkzeuge könnten sein:

- Fist of five oder Delegation Level
- Letzter vernünftiger Moment (LVM)
- Set-Based Design
- Eisenhower-Prinzip
- MoSCoW
- Weighted-Shortest-Job-First (WSJF)
- Relative-Weight

Darüber hinaus ist Teilnehmer:innen bewusst, dass die Dokumentation und Kommunikation von Architekturentscheidungen wichtig ist und Konflikten präventiv entgegen wirken kann. Hierfür eignen sich z.B. Werkzeuge wie Architecture Decision Records.

// end::DE[]

// tag::EN[]

[[LG-4-1]]
==== LG 4-1: Understand the responsibilities of a facilitator role

The participants can distinguish between the role of "facilitator" (supporting a solution process with an unintentional interest in the outcome) and the role of "decision-maker" (contributing to the outcome of the solution with an intentional interest).
They are able to decide, when it is useful and necessary to contribute content with intent from an architectural perspective. They are also aware of the tasks and responsibilities of moderators and dialogue participants.

[[LG-4-2]]
==== LG 4-2: Conduct a moderation including suitable moderation tools

Participants can apply methods and techniques for organizing group situations and conducting discussions in groups to support solution finding and conflict prevention. Moderation techniques could be, for example

- Creativity techniques such as brainstorming
- Call/card queries
- Dot Voting
- Time Boxing
- Mind mapping & matrix visualizations

[[LG-4-3]]
==== LG 4-3: Prepare and implement decision-making with the group

For the role of "decision-maker" (participating with a deliberate interest in the outcome of the solution) and in the role of "moderator", the participants can select suitable decision-making tools and enable architectural decisions in the group. Suitable tools could be

- Fist of five or delegation level
- Last responsible moment (LRM)
- Set-Based Design
- Eisenhower principle
- MoSCoW
- Weighted-Shortest-Job-First (WSJF)
- Relative weight

In addition, participants are aware that the documentation and communication of architectural decisions is important and can prevent conflicts. Architecture Decision Records are a suitable tool for that.

// end::EN[]

