=== {learning-goals}

// tag::DE[]

[[LZ-4-1]]
==== LZ 4-1: Die Verantwortlichkeiten einer Moderationsrolle verstehen

Die Teilnehmer:innen können zwischen Rolle „Moderation“ (mit absichtslosem Interesse am Ergebnis einen Lösungsprozess unterstützen) und Rolle „Entscheider“ (mit absichtsvollem Interesse am Ergebnis der Lösung mitwirken) unterscheiden. 
Sie sind in der Lage aus der Architekturrolle heraus zu entscheiden, wann empfängergerechte Inputs hilfreich wären, um den Lösungsprozess zu unterstützen. Außerdem ist ihnen bewusst, welche Aufgaben und Verantwortlichkeiten Moderator:innen und Gesprächsteilnehmer:innen haben.

[[LZ-4-2]]
==== LZ 4-2: Eine Moderation inkl. passender Moderationswerkzeuge durchführen

Teilnehmer:innen können zur Unterstützung der Lösungsfindung und Konfliktprävention Methoden und Techniken zur Durchführung von Gruppensituationen sowie zur Gesprächsführung in Gruppen anwenden. Moderationstechniken könnten z.B. sein:

- Kreativitätstechniken wie Brainstorming
- Zuruf-/Kartenabfragen
- Dot Voting
- Time Boxing
- Mindmapping & Matrixdarstellungen


[[LZ-4-3]]
==== LZ 4-3: Entscheidungsfindung mit der Gruppe vorbereiten und durchführen

Für die Rolle „Entscheider“ (mit absichtsvollem Interesse am Ergebnis der Lösung mitwirken) und in der Rolle „Moderation“ können die Teilnehmer:innen geeignete Entscheidungsfindungswerkzeuge auswählen und Architektur-Entscheidungen in der Gruppe herbeizuführen. Geeignete Werkzeuge könnten sein:

- Fist of five oder Delegation Level
- Letzter vernünftiger Moment (LVM)
- Set-Based Design
- Eisenhower-Prinzip
- MoSCoW
- Weighted-Shortest-Job-First (WSJF)
- Relative-Weight

Darüber hinaus ist Teilnehmer:innen bewusst, dass die Dokumentation und Kommunikation von Architektur-Entscheidungen wichtig ist und Konflikten präventiv entgegen wirken kann. Hierfür eignen sich z.B. Werkzeuge wie Architecture Decision Records.

// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants can define their role in accordance with the requirements of the specific group situation, between the extremes of “Moderator” (process level) and “Decision maker” (functional level), and can make it transparent in the group.
- To support decision making they can use methods and techniques for the preparation and conduct of group situations and for discussions in groups.
- They can bring about architecture decisions in the group.
- They can provide inputs appropriate to the group’s needs, to support the solution process.

==== What should the participants understand?
- The demands that the role of a moderator places on the architect.
- The difference between the role of the moderator (supporting a solution process with no specific interest in the nature of the resulting solution) and the role of the decision maker/architect (with a specific interest in the resulting solution).
- Which aspects of the moderator role help the architect to in future achieve viable and constructive solutions.
- That in addition to technical aspects, architecture involves a significant level of moderation dexterity to enable smooth interaction with one another.

==== What should the participants know?
- Experience with moderation situations
- Further literature.

[NOTE]
====
**TODO**: explizite Lernziele aus DE übernehmen
====

// end::EN[]

