=== {learning-goals}

// tag::DE[]
==== Was sollen die Teilnehmer können?
- Die TN können ihre Rolle gemäß der Anforderungen der konkreten Gruppensituation zwischen den Polen „Moderator“ (Prozessebene) und „Entscheider“ (fachliche Ebene) bestimmen und können sie in der Gruppe transparent machen.
- Sie können zur Unterstützung der Lösungsfindung Methoden und Techniken zur Vorbereitung und Durchführung von Gruppensituationen sowie zur Gesprächsführung in Gruppen anwenden.
- Sie sind in der Lage, Architekturentscheidungen in der Gruppe herbeizuführen.
- Sie sind in der Lage, empfängergerecht Inputs zu geben, um den Lösungsprozess zu unterstützen.

==== Was sollen die Teilnehmer verstehen?
- Die Anforderungen, die die Rolle eines Moderators an den Architekten stellt.
- Die Abgrenzung zwischen der Rolle des Moderators (mit absichtslosem Interesse am Ergebnis einen Lösungsprozess unterstützen) versus der Rolle des Entscheiders/Architekten (mit absichtsvollem Interesse am Ergebnis der Lösung mitwirken).
- Welche Teile der Moderatorenrolle dem Architekten helfen, in Zukunft für tragfähige und konstruktive Lösungen zu sorgen.
- Architektur beinhaltet neben technischen Aspekten einen hohen Anteil an Moderationsgeschick, um reibungsarm miteinander zu arbeiten.

==== Was sollen die Teilnehmer kennen?
- Erfahrungen mit Moderationssituationen
- Weiterführende Literatur
// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants can define their role in accordance with the requirements of the specific group situation, between the extremes of “Moderator” (process level) and “Decision maker” (functional level), and can make it transparent in the group.
- To support decision making they can use methods and techniques for the preparation and conduct of group situations and for discussions in groups.
- They can bring about architecture decisions in the group.
- They can provide inputs appropriate to the group’s needs, to support the solution process.

==== What should the participants understand?
- The demands that the role of a moderator places on the architect.
- The difference between the role of the moderator (supporting a solution process with no specific interest in the nature of the resulting solution) and the role of the decision maker/architect (with a specific interest in the resulting solution).
- Which aspects of the moderator role help the architect to in future achieve viable and constructive solutions.
- That in addition to technical aspects, architecture involves a significant level of moderation dexterity to enable smooth interaction with one another.

==== What should the participants know?
- Experience with moderation situations
- Further literature.
// end::EN[]

[NOTE]
====
**TODO**: als Lernziele formulieren
====
