=== {learning-goals}

// tag::DE[]

[[LZ-2-1]]
==== LZ 2-1: Gespräche selbständig und strukturiert vorbereiten

Die Teilnehmer:innen verstehen um die Bedeutung und Effektivität einer wohlgeplanten Gesprächsvorbereitung. Sie verstehen, dass sie durch eine intensive Gesprächsvorbereitung in der Lage sind, sich situativ auf das aktuelle Geschehen/ungeplante Veränderungen einzustellen und dass sie ihren Fähigkeiten vertrauen können. Die Teilnehmer:innen können Einzel-, Gruppengespräche sowie Präsentationen auf Basis unterschiedlicher Kommunikationsmodelle einschätzen. Sie verstehen die Struktur eines Gesprächsablaufs und bereiten angemessene spontane Gesprächssituationen und geplante Meetings vor.

[[LZ-2-2]]
==== LZ 2-2: Gespräche souverän und situativ angemessen durchführen

Die Teilnehmer:innen sind in der Lage, eine Unterschiedlichkeit zwischen Sach- und Prozessebene zu erkennen. Sie kennen den Unterschied zwischen Überzeugung, Durchsetzung und Manipulation. Außerdem erkennen sie, wann ein Gruppen- bzw. ein Einzelsetting geeignet ist. Sie kennen Methoden der Gesprächsführung und können sie anwenden, z.B.

- aktives Zuhören
- Fragetechniken
- 4-Quadranten-Modell.
- drei Seiten der Überzeugung nach Aristoteles (Glaubwürdigkeit, Kompetenz, Sympathie)
- Manipulationstechniken (z.B. Reziprozität, Autorität, Sympathie, Knappheit)

[[LZ-2-3]]
==== LZ 2-3: Gespräche inhaltlich und reflektiv nachbereiten können

Die Teilnehmer:innen verstehen die Bedeutung einer Gesprächsnachbereitung für Teilnehmer:innen und als Reflexionsmöglichkeit für sich selbst.

// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants can evaluate one-on-one and group discussions and presentations based on different communication models.
- Participants can independently prepare one-on-one and group discussions in a structured manner.
- Participants can conduct one-on-one and group discussions.
- Participants can carry out the necessary follow-up activities for one-on-one and group discussions.
- The participants have learnt methods for conducting discussions (actively listening, asking questions / follow-up questions, summarising) and how to apply them.

==== What should the participants understand?
- The participants understand the importance and effectiveness of well-planned preparation of discussions.
- The participants understand the structure of the course of a discussion and prepare themselves for it.
- The participants understand the importance of following up discussions.
- The participants can recognise a divergence between the subject level and the process level.
- The participants understand that intensive preparation of a discussion enables them to adapt to current developments and unforeseen changes, and that they can trust their inner freedom and skills.

==== What should the participants know?
- Situations in which the participants conduct one-on-one or group discussions
- Different presentation methods, depending on the respective situation.

[NOTE]
====
**TODO**: explizite Lernziele aus DE übernehmen
====

// end::EN[]

