=== {learning-goals}

// tag::DE[]

[[LZ-2-1]]
==== LZ 2-1: Gespräche selbständig und strukturiert vorbereiten

Die Teilnehmer:innen verstehen um die Bedeutung und Effektivität einer wohlgeplanten Gesprächsvorbereitung. Sie verstehen, dass sie durch eine intensive Gesprächsvorbereitung in der Lage sind, sich situativ auf das aktuelle Geschehen/ungeplante Veränderungen einzustellen und dass sie ihren Fähigkeiten vertrauen können. Die Teilnehmer:innen können Einzel-, Gruppengespräche sowie Präsentationen auf Basis unterschiedlicher Kommunikationsmodelle einschätzen. Sie verstehen die Struktur eines Gesprächsablaufs und bereiten angemessene spontane Gesprächssituationen und geplante Meetings vor.

[[LZ-2-2]]
==== LZ 2-2: Gespräche souverän und situativ angemessen durchführen

Die Teilnehmer:innen sind in der Lage, eine Unterschiedlichkeit zwischen Sach- und Prozessebene zu erkennen. Sie kennen den Unterschied zwischen Überzeugung, Durchsetzung und Manipulation. Außerdem erkennen sie, wann ein Gruppen- bzw. ein Einzelsetting geeignet ist. Sie kennen Methoden der Gesprächsführung und können sie anwenden, z.B.

- aktives Zuhören
- Fragetechniken
- 4-Quadranten-Modell.
- drei Seiten der Überzeugung nach Aristoteles (Glaubwürdigkeit, Kompetenz, Sympathie)
- Manipulationstechniken (z.B. Reziprozität, Autorität, Sympathie, Knappheit)

[[LZ-2-3]]
==== LZ 2-3: Gespräche inhaltlich und reflektiv nachbereiten

Die Teilnehmer:innen verstehen die Bedeutung einer Gesprächsnachbereitung für Teilnehmer:innen und als Reflexionsmöglichkeit für sich selbst.

// end::DE[]

// tag::EN[]

[[LG-2-1]]
==== LG 2-1: Prepare discussions independently and in a structured manner

Participants understand the importance and effectiveness of well-planned interview preparation. They understand that intensive preparation for a meeting enables them to adapt to the current situation/unplanned changes and that they can trust their abilities. Participants are able to assess individual and group discussions and presentations on the basis of different communication models. They understand the structure of a dialogue process and prepare appropriate spontaneous conversation situations and planned meetings.

[[LG-2-2]]
==== LG 2-2: Conduct conversations confidently and appropriately to the situation

Participants are able to recognize the difference between the factual and process levels. They know the difference between persuasion, enforcement and manipulation. They will also recognize when a group or individual setting is suitable. They know methods of dialogue management and can apply them, e.g.

- active listening
- questioning techniques
- 4-quadrant model.
- three sides of persuasion according to Aristotle (credibility, competence, sympathy)
- manipulation techniques (e.g. reciprocity, authority, sympathy, scarcity)

[[LG-2-3]]
==== LG 2-3: Follow up conversations in terms of content and reflection

The participants understand the importance of a follow-up discussion for participants and as an opportunity for reflection for themselves.

// end::EN[]

