=== {learning-goals}

// tag::DE[]
==== Was sollen die Teilnehmer können?
- Die TN können Einzel-, Gruppengespräche sowie Präsentationen auf Basis unterschiedlicher Kommunikationsmodelle einschätzen.
- TN können Einzel- und Gruppengespräche selbstständig strukturiert vorbereiten.
- TN können Einzel- und Gruppengespräche durchführen.
- TN können Einzel- und Gruppengespräche nachbereiten.
- Die TN haben Methoden der Gesprächsführung (aktiv zuhören, fragen/nachfragen, zusammenfassen) kennen- und anwenden gelernt.

==== Was sollen die Teilnehmer verstehen?
- Die Teilnehmer verstehen um die Bedeutung und Effektivität einer wohlgeplanten Gesprächsvorbereitung.
- Die Teilnehmer verstehen die Struktur eines Gesprächsablaufs und stellen sich darauf ein.
- Die Teilnehmer verstehen die Bedeutung einer Gesprächsnachbereitung.
- Die TN sind in der Lage, eine Unterschiedlichkeit zwischen Sach- und Prozessebene zu erkennen.
- Die Teilnehmer verstehen, dass sie durch eine intensive Gesprächsvorbereitung in der Lage sind, sich situativ auf das aktuelle Geschehen/ungeplante Veränderungen einzustellen und dass sie ihrer inneren Freiheit/ihren Fähigkeiten vertrauen können.

==== Was sollen die Teilnehmer kennen?
- Situationen, in denen die TN Einzelgespräche oder Gruppengespräche führen
- Unterschiedliche, der jeweiligen Situation angemessene Präsentationstechnik
// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants can evaluate one-on-one and group discussions and presentations based on different communication models.
- Participants can independently prepare one-on-one and group discussions in a structured manner.
- Participants can conduct one-on-one and group discussions.
- Participants can carry out the necessary follow-up activities for one-on-one and group discussions.
- The participants have learnt methods for conducting discussions (actively listening, asking questions / follow-up questions, summarising) and how to apply them.

==== What should the participants understand?
- The participants understand the importance and effectiveness of well-planned preparation of discussions.
- The participants understand the structure of the course of a discussion and prepare themselves for it.
- The participants understand the importance of following up discussions.
- The participants can recognise a divergence between the subject level and the process level.
- The participants understand that intensive preparation of a discussion enables them to adapt to current developments and unforeseen changes, and that they can trust their inner freedom and skills.

==== What should the participants know?
- Situations in which the participants conduct one-on-one or group discussions
- Different presentation methods, depending on the respective situation.
// end::EN[]

[NOTE]
====
**TODO**: als Lernziele formulieren
====
