=== {learning-goals}

// tag::DE[]

[[LZ-1-1]]
==== LZ 1-1: Kompetenzarten und deren Erlangen kennen und unterscheiden können

Die Teilnehmer:innen können die vier Kompetenzen unterscheiden (Fach-, Methoden-, Sozial- und Persönlichkeits-Kompetenz) und verstehen, dass es unterschiedliche Wege gibt, diese auszubauen (Wissensvermittlung, Übung, Reflexion).

[[LZ-1-2]]
==== LZ 1-2: Grundlagen zu Kommunikationsmodellen und -Typen kennen und zur Reflexion anwenden können

Die Teilnehmer:innen verstehen, dass ihre innere Haltung sich auf Gespräche auswirkt.
Sie kennen verschiedene Kommunikationsmodelle und –typen wie z.B.: 

-	4-Quadranten-Modell
-	4 Seiten einer Nachricht
-	16 Lebensmotive

Die Teilnehmer:innen berücksichtigen, dass Typologien zu Schubladendenken führen können und deshalb vorsichtig genutzt werden sollten. Gleichzeitig erkennen sie deren Nutzen zur Selbstreflexion und zielgruppen- bzw. bedürfnisorientierten Gesprächsführung.

[[LZ-1-3]]
==== LZ 1-3: Feedback als Beitrag zu Lernen verstehen und von Dritten einfordern können 

Teilnehmer:innen sind in der Lage von dritten Personen Feedback einzufordern.
Sie verstehen Feedback als einen Beitrag zu Lernen.
Und sie kennen die Regeln zum Feedback Nehmen und halten diese ein.

[[LZ-1-4]]
==== LZ 1-4: Konstruktiv Feedback geben können 

Die Teilnehmer:innen verstehen, dass sie durch regelmäßige Reflektion eine Klarheit über ihr Eigenbild und Fremdbild erhalten.
Und sie verstehen, dass regelmäßige Feedbacks die konstruktive Zusammenarbeit fördern und damit auch zu nachhaltigen Arbeitsergebnissen beitragen.
Die Teilnehmer:innen kennen die Regeln zum Feedback Geben und halten diese ein.

[[LZ-1-5]]
==== LZ 1-5: Sich selbst reflektieren können

Die Teilnehmer:innen verstehen, dass sie durch regelmäßige Reflektion eine Klarheit über ihr Eigenbild und Fremdbild erhalten.


[[LZ-1-6]]
==== LZ 1-6: Stakeholder der Softwarearchitektur analysieren und Kommunikation zielgruppenorientiert anwenden können

Die Teilnehmer:innen können typische Stakeholder aus Sicht von Softwarearchitekt:innen identifizieren (z.B. Entwickler:innen, Management, Betrieb, Kunden) und deren Anliegen verstehen (z.B. via Maslowsche Bedürfnishierarchie).

Sie können eine Stakeholderanalyse durchführen (z.B.: Modelle und Vorgehen einer Stakeholderanalyse kennen, z.B.: Stakeholder-Map, Beziehungs-Map bzw. Abhängigkeitsanalyse, RACI-Matrix

Die Teilnehmer:innen können Maßnahmen aus der Stakeholderanalyse ableiten (z.B.: Risiken und entsprechende Minderungsmaßnahmen ausarbeiten, kommunizieren und einplanen, Maßnahmen zur Sicherstellung der Stakeholder-Zufriedenheit ausarbeiten, kommunizieren und einplanen, Stakeholder-Kommunikationsplan erstellen)

// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants are familiar with different communication models and types.
- Participants can assess in which typologies they and their dialogue partner find themselves. During this process, they consider that typologies can also lead to stereotyped thinking and should therefore be used with care.
- Participants can adapt their communication to the respective needs of others.

==== What should the participants understand?
- Other people are not the same as me.
- Knowing the other person’s communication type can be useful when communicating with them.
- Content is the least important aspect when speaking.
- People don’t (only) act rationally, and that’s OK!
- Models are too simple, but are nonetheless useful.
- My inner disposition affects the communication.
- It’s wrong to believe that only one person can be right.
- Resource-oriented versus deficient communication.

==== What should the participants know?
- Their own assumptions of how communication works
- Situations in which communication was successful and situations in which it was unsuccessful
- Their own strengths and weaknesses in specific communication situations
- Knowledge of how they wish to improve their own skills

[NOTE]
====
**TODO**: explizite Lernziele aus DE übernehmen
====

// end::EN[]
