=== {learning-goals}

// tag::DE[]

[[LZ-1-1]]
==== LZ 1-1: Kompetenzarten und deren Erlangen kennen und unterscheiden

Die Teilnehmer:innen können die vier Kompetenzen (Fach-, Methoden-, Sozial- und Persönlichkeits-Kompetenz) unterscheiden und verstehen, dass es unterschiedliche Wege gibt, diese auszubauen (Wissensvermittlung, Übung, Reflexion).

[[LZ-1-2]]
==== LZ 1-2: Grundlagen zu Kommunikationsmodellen und -typen kennen und zur Reflexion anwenden

Die Teilnehmer:innen verstehen, dass ihre innere Haltung sich auf Gespräche auswirkt.
Sie kennen verschiedene Kommunikationsmodelle und –typen wie z.B.: 

* 4-Quadranten-Modell
* 4 Seiten einer Nachricht
* 16 Lebensmotive

Die Teilnehmer:innen berücksichtigen, dass Typologien zu Schubladendenken führen können und deshalb vorsichtig genutzt werden sollten. Gleichzeitig erkennen sie deren Nutzen zur Selbstreflexion und zielgruppen- bzw. bedürfnisorientierten Gesprächsführung.

[[LZ-1-3]]
==== LZ 1-3: Feedback als Beitrag zu Lernen verstehen und von Dritten einfordern 

Teilnehmer:innen sind in der Lage, von dritten Personen Feedback einzufordern.
Sie verstehen Feedback als einen Beitrag zu Lernen, kennen die Regeln zum Nehmen von Feedback und halten diese ein.

[[LZ-1-4]]
==== LZ 1-4: Konstruktiv Feedback geben und nehmen 

Die Teilnehmer:innen verstehen, dass sie durch regelmäßige Reflektion eine Klarheit über ihr Eigenbild und Fremdbild erhalten.
Es wird ihnen klar, dass regelmäßige Feedbacks die konstruktive Zusammenarbeit fördern und damit auch zu nachhaltigen Arbeitsergebnissen beitragen.
Die Teilnehmer:innen kennen die Regeln zum Geben von Feedback und halten diese ein.

[[LZ-1-5]]
==== LZ 1-5: Sich selbst reflektieren

Die Teilnehmer:innen verstehen, dass sie durch regelmäßige Reflektion eine Klarheit über ihr Eigenbild und Fremdbild erhalten.


[[LZ-1-6]]
==== LZ 1-6: Stakeholder der Softwarearchitektur analysieren und Kommunikation zielgruppenorientiert anwenden

Die Teilnehmer:innen können typische Stakeholder aus Sicht von Softwarearchitekt:innen identifizieren (z.B. Entwickler:innen, Management, Betrieb, Kunden) und deren Anliegen verstehen (z.B. via Maslowsche Bedürfnishierarchie).

Sie können eine Stakeholderanalyse durchführen mit Werkzeugen wie z.B. 

- Stakeholder-Map
- Beziehungs-Map bzw. Abhängigkeitsanalyse
- RACI-Matrix

Die Teilnehmer:innen können Maßnahmen aus der Stakeholderanalyse ableiten wie z.B. 

- Risiken und entsprechende Minderungsmaßnahmen ausarbeiten, kommunizieren und einplanen
- Maßnahmen zur Sicherstellung der Stakeholder-Zufriedenheit ausarbeiten, kommunizieren und einplanen
- Stakeholder-Kommunikationsplan erstellen

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Recognizing and differentiating between types of competence and their acquisition

Participants can distinguish between the four competences (technical, methodological, social and personal competence) and understand that there are different ways to develop them (knowledge transfer, practice, reflection).

[[LG-1-2]]
==== LG 1-2: Know the basics of communication models and types and apply them for reflection

Participants understand that their inner attitude has an on conversations. They are familiar with different communication models and types, e.g: 

* 4-quadrant model
* 4 pages of a message
* 16 Motives for life

The participants recognize that typologies can lead to pigeonholing and should therefore be used with caution. At the same time, they recognize their usefulness for self-reflection and target group and needs-oriented conversations.

[[LG-1-3]]
==== LG 1-3: Understanding feedback as a contribution to learning and requesting it from third parties 

Participants are to request feedback from third parties. They understand feedback as a contribution to learning, know the rules for receiving feedback and comply with them.

[[LG-1-4]]
==== LG 1-4: Giving and receiving constructive feedback 

The participants understand that regular reflection gives them clarity about how they see themselves and how others see them. They realise that regular feedback promotes constructive cooperation and thus also contributes to sustainable work results. Participants know the rules for giving feedback and comply with them.

[[LG-1-5]]
==== LG 1-5: Self-reflection

The participants understand that regular reflection gives them clarity about how they see themselves and how others see them.

[[LG-1-6]]
==== LG 1-6: Analyse stakeholders of the software architecture and apply communication in a target group-oriented manner

Participants can identify typical stakeholders from the perspective of software architects (e.g. developers, management, operations, customers) and understand their concerns (e.g. via Maslow's hierarchy of needs).

You can carry out a stakeholder analysis using tools such as

- Stakeholder map
- Relationship map or dependency analysis
- RACI matrix

The participants can derive measures from the stakeholder analysis, such as

- Develop, communicate and plan risks and corresponding mitigation measures
- Develop, communicate and plan measures to ensure stakeholder satisfaction
- Create a stakeholder communication plan

// end::EN[]
