=== {learning-goals}

// tag::DE[]
==== Was sollen die Teilnehmer können?
- Die TN erhalten durch regelmäßige Reflektion eine Klarheit über ihr Eigenbild und Fremdbild.
- Die TN sind in der Lage, zu reflektieren.
- Die TN sind in der Lage, von dritten Personen Feedback einzufordern.
- Die TN sind in der Lage, Feedback konstruktiv zu geben.

==== Was sollen die Teilnehmer verstehen?
- Feedback ist ein Beitrag zu Lernen.
- Regelmäßige Feedbacks fördern die konstruktive Zusammenarbeit und tragen damit auch zu nachhaltigen Arbeitsergebnissen bei.
- Techniken zur Reflektion.
- Feedback Regeln zum Geben und Nehmen.

==== Was sollen die Teilnehmer kennen?
- Die Notwendigkeit, zu reflektieren.
- Situationen, in denen die TN selbst Feedback bekommen oder gegeben haben.
// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- Via regular reflection, the participants achieve clarity in respect of their own perception of themselves and how other people perceive them.
- The participants know how to reflect.
- The participants know how to request feedback from others.
- The participants know how to provide constructive feedback.

==== What should the participants understand?
- Feedback contributes to the learning process.
- Regular feedback promotes constructive collaboration and thus also contributes to sustainable work results.
- Reflection techniques.
- Rules for providing and accepting feedback.

==== What should the participants know?
- The need for reflection.
- Situations in which the participants have themselves received or provided feedback.
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
