=== {learning-goals}

// tag::DE[]

[[LZ-3-1]]
==== LZ 3-1: Nützlichkeit von Visualisierung zur effektiven Gesprächsführung und Konfliktprävention erkennen

Die Teilnehmer:innen haben einen Eindruck darüber gewonnen, wie sie Visualisierungstechniken zur Konsensfindung und gemeinsamer Ergebnisentwicklung einsetzen können.
Die Teilnehmer:innen sollen sich ermutigt fühlen, aufzustehen, nach vorne zu gehen und zu visualisieren/malen, was sie denken ohne einen künstlerischen Anspruch zu haben.

[[LZ-3-2]]
==== LZ 3-2: Visualisierungstechniken kennen und passgenau auswählen

Die Teilnehmer:innen kennen Offline- und Online-Visualisierungstechniken wie z.B.: 		

- Whiteboard, Flipchart, Metaplanwände und -karten oder Post-its
- Digitale Whiteboards vs. Office Produkte


// end::DE[]

// tag::EN[]

[[LG-3-1]]
==== LG 3-1: Recognize the usefulness of visualization for effective conversation and conflict prevention

The participants have gained an impression of how they can use visualization techniques to reach consensus and jointly develop results.
Participants should be encouraged to stand up, walk forward and visualize/paint what they think without having artistic pretensions.

[[LG-3-2]]
==== LG 3-2: Know visualization techniques and select them appropriately

The participants are familiar with offline and online visualization techniques such as

- Whiteboard, flipchart, pinboard and cards or post-its
- Digital whiteboards vs. office products

// end::EN[]
