=== {learning-goals}

// tag::DE[]

[[LZ-3-1]]
==== LZ 3-1: Nützlichkeit von Visualisierung zur effektiven Gesprächsführung und Konfliktprävention erkennen

Die Teilnehmer:innen haben einen Eindruck darüber gewonnen, wie sie Visualisierungstechniken zur Konsensfindung und gemeinsamer Ergebnisentwicklung einsetzen können.
Die Teilnehmer:innen sollen sich ermutigt fühlen, aufzustehen, nach vorne zu gehen und zu visualisieren/malen, was sie denken ohne einen künstlerischen Anspruch zu haben.

[[LZ-3-2]]
==== LZ 3-2: Visualisierungstechniken kennen und passgenau auswählen

Die Teilnehmer:innen kennen Offline- und Online-Visualisierungstechniken wie z.B.: 		

- Whiteboard, Flipchart, Metaplanwände und -karten oder Post-its
- Digitale Whiteboards vs. Office Produkte


// end::DE[]

// tag::EN[]

[[LG-3-1]]
==== LG 3-1: Recognise the usefulness of visualisation for effective conversation and conflict prevention

The participants have gained an impression of how they can use visualisation techniques to reach consensus and jointly develop results.
Participants should encouraged to stand up, walk forward and visualise/paint what they think without having artistic pretensions.

[[LG-3-2]]
==== LG 3-2: Know visualisation techniques and select them appropriately

The participants are familiar with offline and online visualisation techniques such as

- Whiteboard, flipchart, metaplan boards and cards or post-its
- Digital whiteboards vs. office products

// end::EN[]
