=== {learning-goals}

// tag::DE[]

[[LZ-3-1]]
==== LZ 3-1: Nützlichkeit von Visualisierung zur effektiven Gesprächsführung und Konfliktprävention erkennen

Die Teilnehmer:innen haben einen Eindruck darüber gewonnen, wie sie Visualisierungstechniken zur Konsensfindung und gemeinsamer Ergebnisentwicklung einsetzen können.
Die Teilnehmer:innen sollen sich ermutigt fühlen aufzustehen, nach vorne zu gehen und zu visualisieren/malen, was sie denken ohne einen künstlerischen Anspruch zu haben.

[[LZ-3-2]]
==== LZ 3-2: Visualisierungstechniken kennen und passgenau auswählen

Die Teilnehmer:innen kennen Offline- und Online-Visualisierungstechniken wie z.B.: 		

- Whiteboard, Flipchart, Metaplanwände und -karten oder Post-its
- Digitale Whiteboards vs. Office Produkte


// end::DE[]

// tag::EN[]
==== What should the participants be able to do?
- The participants have gained an impression of how they can use visualisation techniques for reaching a consensus and for joint development of results.
- The participants should feel motivated to stand up, go to the front and visualise or draw what they’re thinking.

==== What should the participants understand?
- Visualisation can also be used to reach a consensus.
- Visualisation increases transparency and a common understanding.
- Visualisation supports clarification processes.
- Visualisation is a linking topic.
- There’s a difference between visualisation for moderation purposes and someone else visualising their own ideas.

==== What should the participants know?
- How to use whiteboards, flipcharts and metaplan boards and cards
- What is used where in practice
- When visualisation makes sense
// end::EN[]

====
**TODO**: als Lernziele formulieren
====
