:recommended-duration-in-days: 3
:methodical-credits: 0
:technical-credits: 0
:communicative-credits: 30

// tag::DE[]
=== Dauer, Didaktik und weitere Details

Die genannten Zeiten sind Empfehlungen. Die Dauer einer Schulung zum Modul {curriculum-short} sollte mindestens {recommended-duration-in-days} Tage betragen, kann aber länger sein. Anbieter können sich durch Dauer, Didaktik, Art und Aufbau der Übungen sowie der detaillierten Kursgliederung voneinander unterscheiden. Insbesondere die Art der Beispiele und Übungen lässt der Lehrplan komplett offen.

Die erwähnten Techniken, Modelle und Werkzeuge sind Möglichkeiten, den Teilnehmer:innen die Lernziele zu vermitteln. Von diesen Vorschlägen können Trainer:innen abweichen, wenn sie begründen können, warum eine andere Vermittlungstechnik die Lernziele ebenso adressiert. Alle Inhalte sollen an Beispielen der Teilnehmer:innen reflektiert und mit passenden praxisnahen Übungen in deren Alltag transferiert werden.

Lizenzierte Schulungen zu {curriculum-short} tragen zur Zulassung zur abschließenden Advanced-Level-Zertifizierungsprüfung folgende Credit Points bei:

[stripes=none, frame=none, grid=rows]
|===
| Methodische Kompetenz: | {methodical-credits} Punkte
| Technische Kompetenz: | {technical-credits} Punkte
| Kommunikative Kompetenz: | {communicative-credits} Punkte
|===

// end::DE[]

// tag::EN[]
=== Duration, Teaching Method and Further Details

The times stated are recommendations.
The duration of a training course for the {curriculum-short} module should be at least {recommended-duration-in-days} days, but can be longer.
Providers may differ in terms of duration, didactics, type and structure of the exercises and the detailed structure of the course.
In particular, the syllabus leaves the type of examples and exercises completely open.

The techniques, models and tools mentioned are ways of communicating the learning objectives to the participants.
Trainers can deviate from these suggestions if they can justify why a different delivery technique addresses the learning objectives in the same way.
All content should be reflected on using examples from the participants and transferred into their everyday lives with suitable practical exercises.

Licensed training courses for the {curriculum-short} module contribute the following credit points towards admission to the final Advanced Level certification exam:

[stripes=none, frame=none, grid=rows]
|===
| Methodical Competence: | {methodical-credits} Points
| Technical Competence: | {technical-credits} Points
| Communicative Competence: | {communicative-credits} Points
|===

// end::EN[]
