// tag::DE[]
=== Ergänzende Informationen, Begriffe, Übersetzungen

Architekt:innen benötigen Soft Skills in ihrem Alltag. Sie stehen in kontinuierlichem Austausch mit Stakeholdern, Requirements-Ingenieur:innen, Entwicklung und Qualitätssicherung. Dabei treffen sie häufig gemeinsam mit anderen Entwurfsentscheidungen auf Basis der Information aus vielen unterschiedlichen Gesprächen, die sie mit Personen mit unterschiedlichen Interessen geführt haben. In diesem Spannungsfeld müssen sie in der Lage sein, die für die Entscheidung maßgeblich wichtigen Inhalte zu erkennen und herauszuarbeiten. Ihre Entscheidungen wiederum klar nachvollziehbar darzustellen, ist eine weitere Herausforderung.

Oft stehen allzu menschliche Eigenschaften der rein sachlichen Kommunikation im Weg, so dass Missverständnisse und Befindlichkeiten den Entscheidungsprozess und das reibungslose Zusammenarbeiten behindern können. Konflikte können so leicht entstehen.

Die Schulung geht auf die kontextüblichen Arbeitssituationen von Architekt:innen als "Nabe im Rad" konkret ein und liefert pragmatisches Handwerkszeug, um den eigenen Soft-Skills-Baukasten anzureichern und angemessen konstruktiv Herausforderungen in der Architekturarbeit handzuhaben.

Die in der Schulung „Soft Skills für Architekt:innen“ gelernten Inhalte werden in der Prüfung zum iSAQB-CPSA^(R)^-A nicht geprüft. Es wird jedoch von Prüflingen erwartet, dass sie ihre Soft Skills nutzen, um die Lösung, die für die Prüfungsaufgabe gefunden wurde, verständlich zu präsentieren und zu diskutieren.

Soweit für das Verständnis des Lehrplans erforderlich, haben wir Fachbegriffe ins https://github.com/isaqb-org/glossary[iSAQB-Glossar] aufgenommen, definiert und bei Bedarf durch die Übersetzungen der Originalliteratur ergänzt.

// end::DE[]

// tag::EN[]
=== Supplementary Information, Terms, Translations

Architects need soft skills in their day-to-day work. They are in constant dialogue with stakeholders, requirements engineers, development and quality assurance. They often make design decisions together with others based on information from many different discussions they have had with people with different interests. In this field of tension, they must be able to recognise and work out the content that is important for the decision. Presenting their decisions in a clear and comprehensible way is another challenge.

Often, overly human characteristics stand in the way of purely objective communication, so that misunderstandings and sensitivities can hinder the decision-making process and smooth collaboration. Conflicts can easily arise as a result.

The training specifically addresses the contextual work situations of architects as the "hub in the wheel" and provides pragmatic tools to enrich one's own soft skills toolbox and to handle challenges in architectural work in an appropriately constructive manner.

The content learnt in the "Soft Skills for Architects" training course is not tested in the iSAQB CPSA®-A exam. However, candidates are expected to use their soft skills to present and discuss the solution found for the examination task in an understandable way.

Where necessary for understanding the syllabus, we have included technical terms in the https://github.com/isaqb-org/glossary[iSAQB glossary], defined them and supplemented them with translations of the original literature where required.

// end::EN[]


